/**
 * Dockerfile Auto-Generator
 *
 * Generates a production-ready Dockerfile based on detected framework/runtime.
 * Used by the ACR build activity when a user's repo has no Dockerfile.
 */

export type DetectedFramework =
  | "nextjs"
  | "remix"
  | "vite-react"
  | "express"
  | "fastify"
  | "nestjs"
  | "node-generic"
  | "static-html"
  | "python-fastapi"
  | "python-flask"
  | "unknown";

export interface DockerfileGeneratorOptions {
  framework: DetectedFramework;
  port?: number;
  buildCommand?: string;
  startCommand?: string;
  nodeVersion?: string;
  installCommand?: string;
}

/**
 * Detects the framework from package.json dependencies.
 */
export function detectFramework(packageJson: Record<string, any>): DetectedFramework {
  const deps = {
    ...packageJson.dependencies,
    ...packageJson.devDependencies,
  };

  if (deps["next"]) return "nextjs";
  if (deps["@remix-run/node"] || deps["@remix-run/react"]) return "remix";
  if (deps["@nestjs/core"]) return "nestjs";
  if (deps["fastify"]) return "fastify";
  if (deps["express"]) return "express";
  if (deps["vite"] && deps["react"]) return "vite-react";

  return "node-generic";
}

/**
 * Generates a Dockerfile string for the given framework.
 */
export function generateDockerfile(opts: DockerfileGeneratorOptions): string {
  const node = opts.nodeVersion || "20";
  const port = opts.port || 3000;

  switch (opts.framework) {
    case "nextjs":
      return generateNextjsDockerfile(node, port, opts);

    case "remix":
      return generateRemixDockerfile(node, port, opts);

    case "vite-react":
      return generateViteStaticDockerfile(node, port, opts);

    case "nestjs":
      return generateNodeServerDockerfile(node, port, {
        ...opts,
        buildCommand: opts.buildCommand || "npm run build",
        startCommand: opts.startCommand || "node dist/main.js",
      });

    case "fastify":
    case "express":
    case "node-generic":
      return generateNodeServerDockerfile(node, port, opts);

    case "static-html":
      return generateStaticNginxDockerfile();

    default:
      return generateNodeServerDockerfile(node, port, opts);
  }
}

// ─── Framework-specific generators ──────────────────────────────────────────

function generateNextjsDockerfile(node: string, port: number, opts: DockerfileGeneratorOptions): string {
  const install = opts.installCommand || "npm ci";
  const build = opts.buildCommand || "npm run build";

  return `# syntax=docker/dockerfile:1
# Auto-generated by EazyDeploy — Next.js Standalone Build

FROM node:${node}-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package*.json ./
RUN ${install}

FROM node:${node}-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN ${build}

FROM node:${node}-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=${port}
ENV HOSTNAME=0.0.0.0
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE ${port}
CMD ["node", "server.js"]
`;
}

function generateRemixDockerfile(node: string, port: number, opts: DockerfileGeneratorOptions): string {
  const install = opts.installCommand || "npm ci";
  const build = opts.buildCommand || "npm run build";
  const start = opts.startCommand || "npm run start";

  return `# syntax=docker/dockerfile:1
# Auto-generated by EazyDeploy — Remix Build

FROM node:${node}-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package*.json ./
RUN ${install}

FROM node:${node}-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN ${build}

FROM node:${node}-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=${port}
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 appuser
COPY --from=builder /app /app
USER appuser
EXPOSE ${port}
CMD ${JSON.stringify(start.split(" "))}
`;
}

function generateViteStaticDockerfile(node: string, port: number, opts: DockerfileGeneratorOptions): string {
  const install = opts.installCommand || "npm ci";
  const build = opts.buildCommand || "npm run build";

  return `# syntax=docker/dockerfile:1
# Auto-generated by EazyDeploy — Vite Static Build (served via nginx)

FROM node:${node}-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN ${install}
COPY . .
RUN ${build}

FROM nginx:stable-alpine AS runner
COPY --from=builder /app/dist /usr/share/nginx/html
COPY <<EOF /etc/nginx/conf.d/default.conf
server {
    listen ${port};
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files \\$uri \\$uri/ /index.html;
    }
}
EOF
EXPOSE ${port}
CMD ["nginx", "-g", "daemon off;"]
`;
}

function generateNodeServerDockerfile(node: string, port: number, opts: DockerfileGeneratorOptions): string {
  const install = opts.installCommand || "npm ci";
  const hasBuild = !!opts.buildCommand;
  const build = opts.buildCommand || "";
  const start = opts.startCommand || "node src/index.js";

  return `# syntax=docker/dockerfile:1
# Auto-generated by EazyDeploy — Node.js Server

FROM node:${node}-alpine AS deps
RUN apk add --no-cache libc6-compat python3 make g++
WORKDIR /app
COPY package*.json ./
RUN ${install}

FROM node:${node}-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=${port}
ENV HOSTNAME=0.0.0.0
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 appuser
COPY --from=deps /app/node_modules ./node_modules
COPY . .
${hasBuild ? `RUN ${build}` : ""}
USER appuser
EXPOSE ${port}
CMD ${JSON.stringify(start.split(" "))}
`;
}

function generateStaticNginxDockerfile(): string {
  return `# syntax=docker/dockerfile:1
# Auto-generated by EazyDeploy — Static HTML (nginx)

FROM nginx:stable-alpine
COPY . /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;
}
